#!/usr/bin/env bash

staging_dir="$HOME/.music-staging"
music_dir="$HOME/music"
prefix=$(readlink -f "$staging_dir")
prefix_len="$((${#prefix} + 1))"

find "$staging_dir" -maxdepth 3 -type f -name '*.mp3' | while read file; do
    rel_file="${file:prefix_len}"
    slashes=$(tr -dc '/' <<< "$rel_file")
    num_slashes="${#slashes}"
    filename=$(basename "$rel_file")
    songname=${filename%.*}
    mkdir -p "$music_dir/${rel_file%$filename}"
    case "$num_slashes" in
        2)
            mid3v2 -t "$songname" -a "$(cut -d'/' -f 1 <<< $rel_file)" -A "$(cut -d'/' -f 2 <<< $rel_file)" "$file"
            ;;
        1)
            mid3v2 -t "$songname" -a "$(cut -d'/' -f 1 <<< $rel_file)" "$file"
            ;;
        *)
            mid3v2 -t "$songname" "$file"
            ;;
    esac
    artfile="$(dirname "$file")/$songname.jpg"
    if [[ -e "$artfile" ]]; then
        mid3v2 -p "$artfile" "$file"
    fi
    mv "$file" "$music_dir/$rel_file"

echo "$songname"
done

if [[ -n "$DISPLAY" ]]; then
    notify-send -u normal "Processed all music."
fi
